import React, { useState, useEffect } from "react";
import Head from "next/head";
import Header from "./components/Header";
import Hero from "./components/Hero";
import Intro from "./components/Intro";
import IntroSecond from "./components/IntroSecond";
import FeaturedProjects from "./components/FeaturedProjects";
import Services from "./components/Services";
import Technologies from "./components/Technologies";
import Packages from "./components/Packages";
import CallToAction from "./components/CallToAction";
import BlogSection from "./components/BlogSection";
import Footer from "./components/Footer";
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between">
        <Header/>  
        <Hero/> 
        <Intro/>
        <IntroSecond/>
        <FeaturedProjects/>
        <Services/>
        <Technologies/>
        <Packages/>
        <CallToAction/>
        <BlogSection/>
        <Footer/>
      </main>
    </>
  )
}
